### ISSUE TITLE
plugin/Logger.pm line

### ISSUE THREAD

**Issue by Desiderato** [polettix/polebot#1]
shell command: perl monitor -C config

2015/05/14 00:33:46 failed to load 'Logger': syntax error at plugin/Logger.pm line 17, near "/\A \x{01} ACTION \s+ (.*) \x{01} \z/mxs;"
Global symbol "$action" requires explicit package name at plugin/Logger.pm line 18.
Global symbol "$action" requires explicit package name at plugin/Logger.pm line 19.
Compilation failed in require at ./polebot line 280.

**Comment by polettix** [comment]
Corretto
